/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author TUNG
 */
import javax.swing.*;
import java.awt.*;
public class Mainpage extends javax.swing.JFrame {

    /**
     * Creates new form Mainpage
     */
    Login loginframe;
    public Mainpage(Login Login) {
        initComponents();
        this.pack();
        setLocationRelativeTo(null);
        this.loginframe = Login;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialog1 = new javax.swing.JDialog();
        jButton1 = new javax.swing.JButton();
        buttonGroup1 = new javax.swing.ButtonGroup();
        button1 = new java.awt.Button();
        RoutingButton = new javax.swing.JButton();
        AssignVecButton = new javax.swing.JButton();
        AssignMCPbutton = new javax.swing.JButton();
        GetInfoButton = new javax.swing.JButton();

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        button1.setLabel("Logout");
        button1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button1ActionPerformed(evt);
            }
        });

        RoutingButton.setLabel("Routing");
        RoutingButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RoutingButtonActionPerformed(evt);
            }
        });

        AssignVecButton.setText("Assign Vechicles 2 Collectors");
        AssignVecButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AssignVecButtonActionPerformed(evt);
            }
        });

        AssignMCPbutton.setText("Assign MCPs 2 Janitors");

        GetInfoButton.setText("Get Information");
        GetInfoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GetInfoButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(RoutingButton, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(AssignVecButton, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(AssignMCPbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(GetInfoButton, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(155, 155, 155)
                        .addComponent(button1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(103, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(RoutingButton, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(AssignVecButton, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(AssignMCPbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(GetInfoButton, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addComponent(button1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );

        button1.getAccessibleContext().setAccessibleName("LogoutButton");
        button1.getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button1ActionPerformed
        // TODO add your handling code here:
        System.out.println("Mainpage : Clicked Logout button");
        int ret = JOptionPane.showConfirmDialog(this, "Do you want to logout", "Confirm", 0);
        if(ret == 0){
            this.setVisible(false);
            this.dispose();
            this.loginframe.setfield1();
            this.loginframe.setVisible(true);      
        }
    }//GEN-LAST:event_button1ActionPerformed

    private void AssignVecButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AssignVecButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AssignVecButtonActionPerformed

    private void RoutingButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RoutingButtonActionPerformed
        // TODO add your handling code here:
        System.out.println("Mainpage : Clicked Routing button");
        Routing routing = new Routing(this);
        this.setVisible(false);
        routing.setVisible(true);
    }//GEN-LAST:event_RoutingButtonActionPerformed

    private void GetInfoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GetInfoButtonActionPerformed
        // TODO add your handling code here:
        Data_info info = new Data_info();
        info.setVisible(true);
    }//GEN-LAST:event_GetInfoButtonActionPerformed

    /**
     * @param args the command line arguments
     */

   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AssignMCPbutton;
    private javax.swing.JButton AssignVecButton;
    private javax.swing.JButton GetInfoButton;
    private javax.swing.JButton RoutingButton;
    private java.awt.Button button1;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JDialog jDialog1;
    // End of variables declaration//GEN-END:variables
}
